"use client";

interface Props {
  documentType: string;
  documentName: string;
  fields: Record<string, unknown>;
}

const DOC_DESCRIPTIONS: Record<string, string> = {
  cloud_service_agreement: "Standard terms for a cloud SaaS subscription covering access and use, restrictions, privacy, payment, term, warranties, liability, indemnification, and confidentiality.",
  design_partner_agreement: "Agreement for early-access design partner programs covering product access, feedback obligations, IP ownership, and confidentiality.",
  service_level_agreement: "SLA terms defining uptime and response-time targets, service credits, and remedies for cloud services.",
  professional_services_agreement: "Standard terms for professional services engagements covering SOW-based delivery, IP assignment, payment, indemnification, and confidentiality.",
  data_processing_agreement: "GDPR-compliant DPA governing how a provider processes personal data on behalf of a customer.",
  software_license_agreement: "Standard terms for an on-premise software license covering license grant, restrictions, payment, warranties, liability, and confidentiality.",
  partnership_agreement: "Standard terms for business partnerships covering obligations, trademark licensing, payment, confidentiality, indemnification, and liability.",
  business_associate_agreement: "HIPAA-compliant BAA governing a provider's handling of Protected Health Information (PHI).",
  ai_addendum: "Addendum governing AI/ML service usage, covering model training restrictions, IP ownership of inputs and outputs, and AI-specific disclaimers.",
};

function formatKey(key: string): string {
  return key
    .replace(/([A-Z])/g, " $1")
    .replace(/^./, (s) => s.toUpperCase())
    .trim();
}

function formatValue(value: unknown): string {
  if (value === null || value === undefined) return "";
  if (typeof value === "object") return JSON.stringify(value, null, 2);
  return String(value);
}

export default function GenericPreview({ documentType, documentName, fields }: Props) {
  const description = DOC_DESCRIPTIONS[documentType] ?? "";
  const today = new Date().toISOString().split("T")[0];

  const handleDownload = () => {
    const lines = [
      `# ${documentName}`,
      ``,
      description ? `> ${description}` : "",
      ``,
      `## Key Terms`,
      ``,
      ...Object.entries(fields)
        .filter(([, v]) => v !== undefined && v !== null && v !== "")
        .map(([k, v]) => {
          if (typeof v === "object" && v !== null) {
            const entries = Object.entries(v as Record<string, unknown>)
              .filter(([, sv]) => sv)
              .map(([sk, sv]) => `  - ${formatKey(sk)}: ${sv}`)
              .join("\n");
            return `**${formatKey(k)}:**\n${entries}`;
          }
          return `**${formatKey(k)}:** ${v}`;
        }),
      ``,
      `---`,
      `*Generated by Prelegal — CommonPaper standard terms apply. See commonpaper.com for full standard terms.*`,
    ];
    const blob = new Blob([lines.filter(Boolean).join("\n")], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${documentName.replace(/\s+/g, "-")}-${today}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const topLevelFields = Object.entries(fields).filter(([, v]) => typeof v !== "object" || v === null);
  const nestedFields = Object.entries(fields).filter(([, v]) => typeof v === "object" && v !== null);

  const isEmpty = Object.keys(fields).length === 0;

  return (
    <div className="max-w-4xl mx-auto">
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-10 text-gray-800 text-sm leading-relaxed">
        <h1 className="text-2xl font-bold text-center text-[#032147] mb-2">{documentName}</h1>
        {description && (
          <p className="text-center text-gray-500 text-xs mb-8 max-w-2xl mx-auto">{description}</p>
        )}

        {isEmpty ? (
          <div className="border border-dashed border-gray-300 rounded-lg p-8 text-center text-gray-400">
            <p className="text-sm">Fields will appear here as you answer questions in the chat.</p>
          </div>
        ) : (
          <>
            <div className="border border-gray-300 rounded-lg p-6 mb-8">
              <h2 className="font-semibold text-base border-b pb-2 mb-4">Key Terms</h2>
              <div className="space-y-3">
                {topLevelFields.map(([k, v]) => (
                  <div key={k} className="grid grid-cols-3 gap-2 text-sm">
                    <span className="font-medium text-gray-600">{formatKey(k)}</span>
                    <span className="col-span-2 text-gray-900">{formatValue(v)}</span>
                  </div>
                ))}
                {nestedFields.map(([k, v]) => (
                  <div key={k} className="pt-2">
                    <p className="font-medium text-gray-600 text-sm mb-2">{formatKey(k)}</p>
                    <div className="bg-gray-50 rounded-lg p-3 space-y-2 ml-4">
                      {Object.entries(v as Record<string, unknown>)
                        .filter(([, sv]) => sv)
                        .map(([sk, sv]) => (
                          <div key={sk} className="grid grid-cols-3 gap-2 text-sm">
                            <span className="font-medium text-gray-500">{formatKey(sk)}</span>
                            <span className="col-span-2 text-gray-900">{formatValue(sv)}</span>
                          </div>
                        ))}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div className="flex justify-end gap-3 print:hidden">
              <button
                onClick={() => window.print()}
                className="border border-gray-300 hover:bg-gray-50 text-gray-700 font-medium px-5 py-2 rounded-lg text-sm transition-colors"
              >
                Print / Save as PDF
              </button>
              <button
                onClick={handleDownload}
                className="bg-[#209dd7] hover:bg-[#1886ba] text-white font-medium px-5 py-2 rounded-lg text-sm transition-colors"
              >
                Download .md
              </button>
            </div>
          </>
        )}

        <p className="mt-8 text-xs text-gray-400 text-center">
          CommonPaper Standard Terms · CC BY 4.0 · commonpaper.com
        </p>
      </div>
    </div>
  );
}
